### ISSUE TITLE
Looping script and limits PER

### ISSUE THREAD

**Issue by virginsince1997** [mifi/instauto#10]
Good day, thank you for this script,  I'm not fluent in JavaScript script.
How can I use theMaxfollowperday and maxfollowperhour in index.js.
Also how can I loop example.js. thank you

**Comment by mifi** [comment]
Hi. maxFollowsPerHour and maxFollowsPerDay are global limits that prevents follow/unfollow to exceed this number over a sliding window of one hour and day respectively
I updated example now.

Looping is already there, you just put whatever you want to loop inside the for .loop

**Comment by virginsince1997** [comment]
Thanks your very much, but I still don't understand how to loop the script

**Comment by mifi** [comment]
which actions do you want to loop?

**Comment by virginsince1997** [comment]
Follow user followers and unfollow after x days

**Comment by virginsince1997** [comment]
Would appreciate it

**Comment by virginsince1997** [comment]
Hello

**Comment by virginsince1997** [comment]
Still looking forward to looping

**Comment by virginsince1997** [comment]
Please help, Still can't figure out how to loop script

**Comment by mifi** [comment]
Run the program with pm2, as seen in readme example. then it will automatically restart the script
