### ISSUE TITLE
GraphQL URL not working anymore

### ISSUE THREAD

**Issue by ivanpoli** [mifi/instauto#100]
Hi, I have an issue with Instauto, this link is not working anymore: https://www.instagram.com/user?__a=1

Hence the whole instauto is not starting

See screenshot:

![image](https://user-images.githubusercontent.com/106733951/171587863-b80442ff-1768-4b83-8608-b57c6274f3de.png)

Am I somehow getting blocked from IG? What should I do?

**Comment by andbas** [comment]
Seems like IG changed their API a bit, need to investigate how to find a new link to graphql.

**Comment by Brozzor** [comment]
I have exactly the same

**Comment by ivanpoli** [comment]
> Seems like IG changed their API a bit, need to investigate how to find a new link to graphql. I have the same issue

If it's for retrieving followers/following list we have an alternative feasible way: https://stackoverflow.com/a/62722236/4098136

Do you think it could be done with puppeter?

**Comment by mifi** [comment]
related https://github.com/mifi/SimpleInstaBot/issues/125

**Comment by ivanpoli** [comment]
Thank you very much, it's fixed in the latest release! I'm going to close this issue.
