### ISSUE TITLE
Instauto does not find the close button after liking a picture

### ISSUE THREAD

**Issue by andinch** [mifi/instauto#101]
The bot always successfully follows the user. After it is supposed to link some images, the following error message appears.

`2022-06-04T12:06:09.243Z Failed to process follower XXX Error: Evaluation failed: Error: Close button not found (aria-label)                                                                                              at likeCurrentUserImagesPageCode (__puppeteer_evaluation_script__:70:36)                                                at ExecutionContext._evaluateInternal (C:\PATH\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)                                                           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                           at async ExecutionContext.evaluate (C:\PATH\instauto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)                                                              at async likeUserImages (C:\PATH\instauto\node_modules\instauto\src\index.js:588:5)                                                                                                           at async processUserFollowers (C:\PATH\instauto\node_modules\instauto\src\index.js:672:13)                                                                                                    at async Object.processUsersFollowers [as followUsersFollowers] (C:\PATH\instauto\node_modules\instauto\src\index.js:696:9)                                                                   at async C:\PATH\instauto\example.js:105:5`

It then jumps to the next user.

**Comment by Luen** [comment]
Seems like they changed it up again. 
`document.querySelector('svg[aria-label="Close"]')` seems to work.

**Comment by andinch** [comment]
Thank you, that could solve the problem.

**Comment by mifi** [comment]
thanks for testing tihs. releasing a new version
