### ISSUE TITLE
Login button not found

### ISSUE THREAD

**Issue by therightprofile** [mifi/instauto#106]
Hello,

First of all I'd like to say thank you for developing this. 

Suddenly today after a week of use and upon a reboot of my raspberry I get this:

_Login button not found. Maybe you can help me click it? And also report an issue on github with a screenshot of what you're seeing :)_

I tried to click the login button myself but it doesn't help the bot resume its work.

The only thing that helped was placing a break on line 922 to end the loop.

![lol](https://user-images.githubusercontent.com/45567192/175780271-a4ff73d4-5642-4ee8-99ea-f7fe38f4b44e.jpg)

**Comment by NomanBaigA** [comment]
same issue

**Comment by mifi** [comment]
please provide me with the html of the login button (see template)

**Comment by mifi** [comment]
and maybe a screenscast showing what's going on. i just tested and login works for me

**Comment by NomanBaigA** [comment]
Yes, I tried the whole process again and now it's working. Thanks :)
