### ISSUE TITLE
Timeout exceeded while waiting for event

### ISSUE THREAD

**Issue by belqit** [mifi/instauto#115]
![image](https://user-images.githubusercontent.com/44238749/181738633-11d47878-8cdc-4c53-9694-fadb33c75336.png)

the bot crashes on startup, it says that it can't reach my ig page, but i can see my ig page on google chrome

instauto 9.1.9

**Comment by mifi** [comment]
Hi. Can you try to set your own Bio (profile) on your account, to something. see if that helps

**Comment by belqit** [comment]
already did it.

it fails here:
![image](https://user-images.githubusercontent.com/44238749/181766446-34601dd2-bd21-40a1-a9ed-89e0cca89e0e.png)
that api is not called

**Comment by mifi** [comment]
Hmm. yes. I can reproduce the problem. also the Bio fix did not work for me etiher. For some reason instagram doesn't send this request when running in puppeteer. When opening the page on my normal chrome (same user), it works.

I tried:
- Identical user agent
- Increase resolution of the browser window (with 1025)

Not sure why it's not sending that request...

**Comment by belqit** [comment]
this is my fix

`async function navigateToUserAndGetData(username) {
    const cachedUserData = userDataCache[username];

    if (isAlreadyOnUserPage(username)) {
      // assume we have data
      return cachedUserData;
    }

    if (cachedUserData != null) {
      // if we already have userData, just navigate
      await navigateToUserWithCheck(username);
      return cachedUserData;
    }

    
    await navigateToUserWithCheck(username);
    
    var body = await page.content()
    const r = body.split(/\r?\n/);
    var userData;
    for (var q of r) {
      if (q.includes("edge_followed_by")) {
        q = q.split(",[],[")[1]

        q = q.split("]]]")[0]
        q = JSON.parse(q)
        q = q.data.__bbox.result.response
        q = q.replace(/\\/g, "");
        q = JSON.parse(q)

        userData = q.data.user
        break;
      }
    }
    
    userDataCache[username] = userData;
    return userData;
  }`

**Comment by mifi** [comment]
not sure how that works. I cannot find `edge_followed_by` in my html

**Comment by belqit** [comment]
I have it.

Did you check on your profile page html?

**Comment by mifi** [comment]
yes. instagram.com/myaccount
are you using mobile or desktop User agent?

**Comment by belqit** [comment]
Desktop, I didn't change my user agent

Il ven 29 lug 2022, 18:14 Mikael Finstad ***@***.***> ha
scritto:

**Comment by mifi** [comment]
I have two accounts. One works with instauto and the other one gets Timeout. (doesn't sent the `web_profile_info` request). I did notice a difference:

- account 1: does send web_profile_info, inside HTML it has: `<script>qpl_inl("...","tierTwo");</script>`
- account 2: doesn't send web_profile_info, inside HTML it has: `<script>qpl_inl("...","tierThree");</script>`

so I'm thinking instagram gives different users different versions of the frontend code. and the new version no longer sends the web_profile_info request

**Comment by belqit** [comment]
i have `tierOne`,`tierTwo` and `tierThree`.
the `edge_followed_by` part is between `tierTwo` and `tierThree`, it starts with `requireLazy(["JSScheduler","ServerJS","ScheduledApplyEach"],function(JSSch...`

**Comment by mifi** [comment]
I tried your JS and it seems to work on our own profile, but when navigating to other accounts, the `edge_followed_by` doesn't seem to exist in the HTML. did you find any workaround for that?

**Comment by belqit** [comment]
for me is working even other profile page, every profile page have a different json.

**Comment by mifi** [comment]
I have combined your solution with some other workarounds, and that seems to work. releasing a new version.
