### ISSUE TITLE
Stuck on 4/5] Linking dependencies...

### ISSUE THREAD

**Issue by Kmfernan5** [mifi/instauto#131]
Stuck on 4/5] Linking dependencies...
[---------------------------------------------------------------------------------------------------------------] 0/254

**To Reproduce**
Share your setting and describe what the bot is doing before you receive the error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Wiindws 11
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

 add puppeteer instauto
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[---------------------------------------------------------------------------------------------------------------] 0/254

**Comment by mifi** [comment]
I think this a problem with yarn/npm, not with instauto
