### ISSUE TITLE
Failed to follow user (button did not change state)

### ISSUE THREAD

**Issue by oteri4u** [mifi/instauto#14]
Failed to follow user (button did not change state)

Works on my local linux computer but I get this error on my remote linux server

LOCAL LINUX COMPUTER
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2019.4
Codename:       kali-rolling

REMOTE LINUX SERVER (GOOGLE CLOUD)
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

**Comment by mifi** [comment]
Try to run with headless false and see if you get an error msg from instagram. Is your server on same ip as computer?

**Comment by oteri4u** [comment]
headless false returns error failed to launch chrome

**Comment by oteri4u** [comment]
Please which platform can I deploy to without this error: Failed to follow user (button did not change state)

**Comment by mifi** [comment]
Sounds like your server has no GUI. Maybe you can do ssh into it with X11 forwarding (ssh -Y host) and see if it works. It’s hard to know what’s wrong without seeing what the display shows. Or maybw you can add to the code to take a screenshot after it catches the error.

**Comment by oteri4u** [comment]
chrome runs very slow when i try to do x11 forwarding on my server

**Comment by oteri4u** [comment]
I added the screen shot code, the problem is the action gets blocked when it comes from my server. link to screen shot https://mega.nz/#!xo1nmChS!_hTd7xBOpn43PUcz3wuEkOXpA0LZ0XppERc68BVXYbM

Please is there a way to get around this

**Comment by mifi** [comment]
Like I said before and stated in readme, make sure your server has a normal home internet provider IP address and not cloud. Nothing I can do to solve this. Maybe try to use a VPN or a tunnel thru to a server running in your home. Maybe instabot.py has some discussion around these problems:
https://github.com/instabot-py/instabot.py
