### ISSUE TITLE
bug : TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by Brozzor** [mifi/instauto#15]
Hello , I execute the scrpit it launches well, enter the nickname and the password then suddenly the window closes.
thanks.

`TypeError: Cannot read property 'click' of undefined
    at module.exports (F:\document\NODE\instauto\node_modules\instauto\index.js:511:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async F:\document\NODE\instauto\example.js:51:22
Closing browser`

**Comment by davidbaumann** [comment]
Hello

What language is Instagram set to?
It looks for a button with caption "Log In", see index.js line 510.

David

**Comment by Brozzor** [comment]
thank you for help
My language is French

**Comment by davidbaumann** [comment]
Actually, this is a problem with instauto with all non-english users.
