### ISSUE TITLE
Private Follow Not Working

### ISSUE THREAD

**Issue by JulienLevallois** [mifi/instauto#2]
Hi ! I try to use your bot but it not works with private profile. The bot is not able to find the follow button when the user is private... Do you know why ?
Its weird because the button have the same text value "Follow"

Thanks

**Comment by JulienLevallois** [comment]
![image](https://user-images.githubusercontent.com/5727223/59566425-30046300-902e-11e9-80eb-792f1dfd401b.png)

**Comment by mifi** [comment]
Hi. What's the error you are getting? The code will check if the button changed value from "Follow" to "Following", and if it doesn't it will show a warning, but it should not fail. But there may be a bug
See https://github.com/mifi/instauto/blob/master/index.js#L156

**Comment by balazsnemeth** [comment]
Same issue for me.

Here is an example:
```
Navigating to user guerrooo19
{ followedByCount: 836, followsCount: 476 }
Failed to process follower guerrooo19 Error: Follow button not found
    at followCurrentUser (/Users/nbalazs/Work/projects/digitalNomad/instafollow/node_modules/instauto/index.js:151:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

But if you check https://www.instagram.com/guerrooo19/, you can see the Follow button there but somehow the program is not able to find it. 

I tried to add 2 or 5 sec sleep before try to follow, but it did not help.

**Comment by balazsnemeth** [comment]
Here is 2 `button` example:

Private Account:
 <button class="BY3EC  _0mzm- sqdOP  L3NKy       " type="button">Follow</button>
Public Account:
 <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   ">Follow</button>

So a hack like this works (keep in mind, I've started using puppeteer 1h ago... ):

```
async function findFollowUnfollowButton(text) {
    const elementHandles = await page.$x("//button[contains(text(), '" + text + "')]");
    if (elementHandles.length !== 1) {

      const actionButtonTitle = await page.$eval('header button[type="button"]', el => el.textContent.trim());
      if (actionButtonTitle.indexOf(text) > -1) {
        return await page.$('header button[type="button"]');
      }

      return undefined;
    }
    return elementHandles[0];
  }
```

**Comment by mifi** [comment]
Thanks! I have now fixed this in the latest version
