### ISSUE TITLE
Unhelpful error message "Follow button not found"

### ISSUE THREAD

**Issue by tobyink** [mifi/instauto#21]
I get this error message occasionally:

```
Failed to process follower XXXXXXXX Error: Follow button not found
    at followCurrentUser (/home/YYYY/bin/instauto-master/node_modules/instauto/index.js:216:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is for users that I already follow, so it makes sense the follow button isn't found. Probably instauto just shouldn't be visiting them if I already follow them.

**Comment by mifi** [comment]
agree. pr welcome

**Comment by mrkrumhausen** [comment]
Would make sense to store manually followed users in the json file, so they also can be unfollowed at a later time.
