### ISSUE TITLE
List of current_follow_requests

### ISSUE THREAD

**Issue by qadirsuh** [mifi/instauto#27]
Can we fetch users list ==> current_follow_requests
i.e 
https://www.instagram.com/accounts/access_tool/current_follow_requests

**Comment by mifi** [comment]
Why do you need this?

**Comment by qadirsuh** [comment]
I need this because, I want to fetch this list and cancel all requests that doesn't follow me back

**Comment by qadirsuh** [comment]
Is this already implemented in your code? I just saw the readme file it states

> Unfollow users that don't follow us back. Will not unfollow any users that we recently followed.

**Comment by mifi** [comment]
No, not implemented. But the bot will indeed cancel requests after a while

**Comment by mohsentaleb** [comment]
@qadirsuh Instauto will only track users followed by itself not the ones you sent follow requests to, manually or using other tools. So for getting a list of those who are not tracked, you need to get them from https://www.instagram.com/accounts/access_tool/current_follow_requests and pass it to bot manually or write a new method to do the leg work for you.

**Comment by Xaeed** [comment]
> @qadirsuh Instauto will only track users followed by itself not the ones you sent follow requests to, manually or using other tools. So for getting a list of those who are not tracked, you need to get them from https://www.instagram.com/accounts/access_tool/current_follow_requests and pass it to bot manually or write a new method to do the leg work for you.

already created a PR which will get which list down all follow requests sent by user , later on we can create another method or use existing one to cancel these follow request.
