### ISSUE TITLE
Changes on the instagram page 06.11.20. authorization Error.

### ISSUE THREAD

**Issue by ivys17** [mifi/instauto#34]
You need to make changes to index.js
  const isLoggedIn = async () => (await page.$x('//nav')).length === 2;    - old
  const isLoggedIn = async () => (await page.$x('//nav')).length === 1;   - new

**Comment by mifi** [comment]
Thanks! I fixed it instead like this:
```js
const isLoggedIn = async () => (await page.$x('//*[@aria-label="Home"]')).length === 1;
```
...hopefully more robust.

Try 7.0.3

**Comment by mostolesmakers** [comment]
mm dont work for me
![image](https://user-images.githubusercontent.com/73793408/98439145-17e42680-20f0-11eb-973a-81c7cfca7d8b.png)

**Comment by mifi** [comment]
That’s odd. Works for me. Can you confirm you have the newest version?
`cat node_modules/instauto/package.json`

**Comment by mostolesmakers** [comment]
sorry, works ok now
