### ISSUE TITLE
User data not found

### ISSUE THREAD

**Issue by deyanpeychev00** [mifi/instauto#40]
I'm getting the following error when trying to execute any action on a particular user (e.g. follow their followers):

```
Failed to follow user followers, continuing Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined
    at __puppeteer_evaluation_script__:1:61
```

Do you have an idea of what may cause this error and how to fix it?

**Comment by mifi** [comment]
Does it happen consistently, and even if you log out and in again? what happens on the instagram page when you see it?

**Comment by deyanpeychev00** [comment]
Yes, it always happens. The Instagram page remains unchanged. I see `Waiting <n> seconds` on the console, but after the seconds pass, nothing further happens as well.

**Comment by tobyink** [comment]
I'm getting the same. Just started happening today after I've been using instauto for months.

**Comment by mifi** [comment]
That's strange. I haven't seen this error.

The only thing I can think of is to try is to open developer tools and in the console enter `window._sharedData.entry_data.ProfilePage[0]`
Then see what's inside there

**Comment by mifi** [comment]
And if the above gives an error, try this:

```js
JSON.parse(Array.from(document.getElementsByTagName('script')).find(el => el.innerHTML.startsWith('window._sharedData')).innerHTML.replace(/^window._sharedData ?= ?({.*});$/, '$1')).entry_data.ProfilePage[0].graphql.user
```

**Comment by Xaeed** [comment]
@deyanpeychev00  if issue still exists, can you give steps to reproduce along screenshots . I can have a look into it and resolve this issue.

**Comment by hanvia** [comment]
This happened to me, looks like Instagram caught suspicious activity and blocked specific accounts accessing `ProfilePage`.
They somehow allow login but can't find anything with `window._sharedData.entry_data.ProfilePage[0]`.

**Comment by mifi** [comment]
@hanvia thanks for checking. Did you confirm that the page was loaded on your current profile? Did you try refreshing? or logging out and back in? What about opening another browser (chrome) and see if the data is there?

**Comment by mifi** [comment]
I think this has been resolved, we are no longer using window._sharedData
