### ISSUE TITLE
"Session closed" headless Chromium doesn't respond but not exiting

### ISSUE THREAD

**Issue by timothe** [mifi/instauto#45]
Similar to #19, I get a bunch of:
`Failed to follow user followers, continuing Error: Protocol error (Page.navigate): Session closed. Most likely the page has been closed.`
from the bot after a while. 
It's running headless.
I think it should catch that issue and restart a session or exit so pm2 can take it back up.

**Comment by mifi** [comment]
Would be nice to know more about your system (OS etc). Does the same happen with headless: false? Can you reproduce the problem? How long until it happens? Closing: can continue discussion in #19
