### ISSUE TITLE
Bot not unfollowing

### ISSUE THREAD

**Issue by apollotsantos** [mifi/instauto#52]
Hi, 

For some reason my bot is not unfollowing as it should. Could you help me understandig three things? 

1. Does the bot follows or unfollows first when it start? (SimpleInstaBot unfollows first)
2. How do I set the variable dontUnfollowUntilTimeElapsed? I don't seem to understand those multiplications
3. Is there any difference between this and SimpleInstaBot, in terms of the pupeteer implementation?

**Comment by mifi** [comment]
Hi
1. Currently it follows first. See https://github.com/mifi/instauto/blob/master/example.js I can change this so it instead unfollows first like SimpleInstaBot.
2. `3 * 24 * 60 * 60 * 1000` means three days (in milliseconds). I'll update the example
3. SimpleInstaBot doesn't use puppeteer, but it uses an electron window. which is also chrome and similar, but not exactly the same.

**Comment by mifi** [comment]
I have now updated the example

**Comment by apollotsantos** [comment]
Hi, please take a look at the following image. I've modified the example to unfollow first, and then follow. It seems that it reaches the daily limit, wait 10 minutes and unfollows more, until realising that the daily limit is already reached.

![image](https://user-images.githubusercontent.com/25730751/113617869-4594b380-962d-11eb-8810-7222b19ba1a3.png)

**Comment by mifi** [comment]
what does it say about this?

```
  logger.log(`Have followed/unfollowed ${getNumFollowedUsersThisTimeUnit(hourMs)} in the last hour`);
  logger.log(`Have followed/unfollowed ${getNumFollowedUsersThisTimeUnit(dayMs)} in the last 24 hours`);
  logger.log(`Have liked ${getNumLikesThisTimeUnit(dayMs)} images in the last 24 hours`);
```
and what's your daily limit and your other parameters?

**Comment by apollotsantos** [comment]
How would I issue those logger commands? 

My daily limit is set to 120 and 10/hour

**Comment by mifi** [comment]
Those are automatically issues when starting up, no?

**Comment by apollotsantos** [comment]
Yes, my bad. I've edited my comment with the results. It seems that the action count was 143 while my limit was 120

**Comment by mifi** [comment]
if it had followed 143 the last 24 hours and your limit is 120, then that explains why it diddn't want to follow/unfollow any more. if it is started following again, then it should be because time has passed so that there is no longer 143 followed last 24 hours (maybe some time passed). it continously calculates a window of actions  in the previous 24 hours

**Comment by doge0007** [comment]
hello, the bot does not stop following. button not found

![unf](https://user-images.githubusercontent.com/103456247/168180445-eefce403-8969-4a4f-b50e-64ef32bc8203.jpg)

**Comment by mifi** [comment]
@doge0007 please provide a screnshot of the browser window when the error occurs and a html dump of the button using developer tools

**Comment by doge0007** [comment]
![error unfollow](https://user-images.githubusercontent.com/103456247/169926625-da143055-b6e7-4591-b5b4-65cfb5b151f3.jpg)

**Comment by mifi** [comment]
is this still happening with the newest version? would be nice to see how the html of the unfollow button looks like

**Comment by doge0007** [comment]
Hello, after the previous version I have not had that problem at the moment. Thank you!

**Comment by mifi** [comment]
cool!
