### ISSUE TITLE
Login using Session cookies

### ISSUE THREAD

**Issue by toppersdesk** [mifi/instauto#53]
I was looking for an API like this, which is still maintained I guess. Great work by the developers. I stumbled upon some ideas to improve this:
1.) if I could be able to install this on a server ([a method like this](http://www.youtube.com/watch?v=t_D6MTjTbls)) and let it run for a long period + sending an error notification on email if something went wrong.

2.) (Maybe better approach OR already in use which I'm unaware of) Using session cookies to login ([similar to this service](https://phantombuster.com/automations/instagram/10274/instagram-auto-follow/tutorial#authenticate-to-instagram)) to avoid bot detection.

I'm completely new to node.js but gonna try making the first option work. I will appreciate it if someone could help with this.

**Comment by mifi** [comment]
Hi

1. I think running it on a server is a bit risky because Instagram thinks that it not a real user due to a cloud IP
2. I'm not sure if cookies will improve the situation. If instgram sees the request coming from a cloud IP, they could still suspect something wrong. See here for how to set up on a server: https://github.com/mifi/instauto#running-with-pm2

**Comment by toppersdesk** [comment]
Thanks a lot @mifi for this great API. Currently, I'm using your Simpleinstabot but there are two reasons I wanna go with server setup, firstly the simpleinstabot needs a stable internet connection with higher data limits (as it loads videos/images in posts for liking), and secondly, my laptop needs to be ON all day (otherwise the process get disrupted and bot gives unexpected results), which is not I plan to do.
I tried [their ](https://phantombuster.com/automations/instagram/10274/instagram-auto-follow/tutorial#authenticate-to-instagram) service and it's pretty smoothly running on my other account. I'm still trying to find out how they solved the cloud IP problem.

**Comment by mifi** [comment]
how many do you follow per hour with that service?

**Comment by toppersdesk** [comment]
the service limits us to follow max 5 per launch and max 4 launches of script per hour.
But I just use it to do 2 follows/ hr for 24hrs.

**Comment by mifi** [comment]
ok, you can still login by using session cookies in instauto, but you need to manually put the cookies into cookies.json in the correct format.



> Will the stealth plugin help to hide the cloud IP?

no, it will just make puppeteer look less like a headless browser and more like a normal google chrome

**Comment by toppersdesk** [comment]
Okay, I will try the stealth plugin with puppeteer in instauto because I couldn't find the option to run script on startup in simpleinstabot and no option to choose headless browser to reduce the internet data usage. Otherwise, simpleinstabot is perfect for the use. Thanks man.

**Comment by mifi** [comment]
see the issue i linked about for how to do stealth. headless browser will not reduce internet data usage but it will allow to run without any window GUI. see puppeteer docs.
