### ISSUE TITLE
Implement support for likes photos only (without following)

### ISSUE THREAD

**Issue by zsvendo** [mifi/instauto#63]
I just want to like photos of competitors' users, I don't want to follow and unloffow, I tried to leave the parameters with 0 but it gives an error.

remembering that I just want to give likes photos

Attached images

![1](https://user-images.githubusercontent.com/28624361/121456201-1592c500-c97c-11eb-9429-691d4d33ff23.JPG)
![2](https://user-images.githubusercontent.com/28624361/121456203-162b5b80-c97c-11eb-9962-a11a1365f20b.JPG)
![3](https://user-images.githubusercontent.com/28624361/121456378-5be82400-c97c-11eb-8a5c-b76534a09708.JPG)

**Comment by RFlamant** [comment]
@mifi Do you think you will go on this feature ? Anyway, great work thanks a lot :)

**Comment by mifi** [comment]
this is now implemented
