### ISSUE TITLE
Not loggin in

### ISSUE THREAD

**Issue by albrox** [mifi/instauto#68]
I tried the OSX Desktopversion, which gives me the following error:

WARNING: Login has not succeeded. This could be because of an incorrect username/password, or a "suspicious login attempt"-message. You need to manually complete the process.

Even though the login has succeeded

**Comment by mifi** [comment]
what do you see on screen after this message occurs? in the instagram window

**Comment by albrox** [comment]
I am on the startscreen of instagram, perfectly logged in. In german though

**Comment by mifi** [comment]
Could you share the HTML (and maybe a screenshot) of the login page before the bot logs in?

- delete cookies
- start the bot
- then when the bot is on the login screen, pause execution of instauto, e.g by CTRL-Z in the terminal
- Using the Web Inspector (F12) in puppeteer chromium window, go to the Elements tab, right click on the HTML tag and select Copy->Copy outerHTML. Then paste that here

I want to see how the language selector looks like in HTML

<img width="609" alt="Screenshot 2021-09-23 at 16 57 55" src="https://user-images.githubusercontent.com/402547/134488399-44d0e060-5c9a-4e54-bf08-90546fe6035d.png">

**Comment by mifi** [comment]
See also https://github.com/mifi/SimpleInstaBot/issues/28#issuecomment-732482082
