### ISSUE TITLE
Maximize window instauto default

### ISSUE THREAD

**Issue by joelemanoel** [mifi/instauto#76]
Hi @mifi,

I think it would be interesting to leave Instauto maximized in SimpleInstaBot.

In the instauto, in "example.js" it would be possible to add in the launcher the option: `defaultViewport: null`.

**Comment by joelemanoel** [comment]
Additional: In SimpleInstaBot on BrowserWindow the function is used: `win.maximize()`

**Comment by mifi** [comment]
Hi! Why is maximizing useful? I believe this issue belongs to simpleInstaBot, not instauto.
