### ISSUE TITLE
instauto.likeCurrentUserImages is not a function

### ISSUE THREAD

**Issue by zirvu** [mifi/instauto#83]
Hi, i tired to use likeCurrentUserImages but i got this error

instauto.likeCurrentUserImages is not a function
![image](https://user-images.githubusercontent.com/93853818/160041038-ea5d7854-db9e-4b67-b226-ce649c9a1fbf.png)
![image](https://user-images.githubusercontent.com/93853818/160041069-e7f3bc9e-ea86-45da-9dfb-d62c32632e1c.png)

**Comment by mifi** [comment]
have exposed this function in the newest version
